name: Deploy Frontend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/20252-progeficaz-projeto-final-frontend-clinica-erp-front/clinic-scheduling-frontend
            git pull origin main
            npm install
            npm run build
            sudo rm -rf /var/www/clinic-frontend/*
            sudo cp -r dist/* /var/www/clinic-frontend/
            sudo systemctl reload nginx
